services:
  Contexts.Backoffice.Backend.product.reviews.domain.ProductReviewsRepository:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/infrastructure/persistence/postgres-typeorm/TypeOrmProductReviewsRepository
    arguments: ['@Backoffice.ConnectionManager']
  Contexts.Backoffice.Backend.product.reviews.create.ProductReviewsCreator:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/application/create/ProductReviewsCreator
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.domain.ProductReviewsRepository", "@Backoffice.EventBus"]
  Contexts.Backoffice.Backend.product.reviews.create.AddProductReviewsCommandHandler:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/application/create/AddProductReviewsCommandHandler
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.create.ProductReviewsCreator"]
  Contexts.Backoffice.Backend.product.reviews.generate.content.embedding.ProductReviewsEmbeddingGenerator:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/infrastructure/persistence/ollama/generate-content-embeddings/NomicProductReviewsEmbeddingGenerator
  Contexts.Backoffice.Backend.product.reviews.generate.content.embedding.ProductReviewsEmbeddingGeneratorService:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/application/generate-embedding/ProductReviewsEmbeddingGeneratorService
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.generate.content.embedding.ProductReviewsEmbeddingGenerator", "@Contexts.Backoffice.Backend.product.reviews.domain.ProductReviewsRepository"]
  Contexts.Backoffice.Backend.product.reviews.publish.reviews.when.negative.threshold.exceeded.NegativeThresholdSurpassedPublisher:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/application/publish-reviews-when-negative-threshold-exceeded/NegativeThresholdSurpassedPublisher
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.domain.ProductReviewsRepository"]
  Contexts.Backoffice.Backend.product.reviews.update.to.negative.review.ToNegativeUpdateReviewSentimentUpdater:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews/application/update-to-negative-review/ToNegativeUpdateReviewSentimentUpdater
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.domain.ProductReviewsRepository"]
