services:
  Apps.Backoffice.Backend.subscribers.rabbitmq.sentiment.classifier.ClassifyReviewContentOnProductReviewsCreated:
    class: ../../../../subscribers/rabbitmq/review-sentiment-classifier/classify-review-content/ClassifyReviewContentOnProductReviewsCreated
    arguments: ["@Contexts.Backoffice.Backend.product.sentiment.classifier.application.create.LabelSentimentFromReviewContentCommandHandler"]
    tags: [{ "name": "domain-event-subscriber" }]
  Apps.Backoffice.Backend.subscribers.rabbitmq.IncreaseNegativeReviewOnNegativeProductReviewDetected:
    class: ../../../../subscribers/rabbitmq/product-reviews-config/increase-negative-review/IncreaseNegativeReviewOnNegativeProductReviewDetected
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.application.increment.negative.reviews.IncrementProductReviewsConfigNegativeReviewsOnProductReviewsCreatedCommandHandler"]
    tags: [{ "name": "domain-event-subscriber" }]
  Apps.Backoffice.Backend.subscribers.rabbitmq.IncrementProductReviewsConfigTotalReviewsOnProductReviewsCreated:
    class: ../../../../subscribers/rabbitmq/product-reviews-config/increment-product-reviews-config-total-reviews/IncrementProductReviewsConfigTotalReviewsOnProductReviewsCreated
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.application.increment.IncrementProductReviewsConfigTotalReviewsOnProductReviewsCreatedCommandHandler"]
    tags: [{ "name": "domain-event-subscriber" }]
  Apps.Backoffice.Backend.subscribers.rabbitmq.CreateProductReviewsConfigOnProductCreated:
    class: ../../../../subscribers/rabbitmq/product-reviews-config/create/CreateProductReviewsConfigOnProductRegistered
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.application.create.CreateProductReviewsConfigOnProductRegisteredCommandHandler"]
    tags: [{ "name": "domain-event-subscriber" }]
  Apps.Backoffice.Backend.subscribers.rabbitmq.GetProductReviewsOnNegativeThresholdSurpassed:
    class: ../../../../subscribers/rabbitmq/product-reviews/find-when-negative-threshold-surpassed/GetProductReviewsOnNegativeThresholdSurpassed
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.publish.reviews.when.negative.threshold.exceeded.NegativeThresholdSurpassedPublisher"]
    tags: [{ "name": "domain-event-subscriber" }]
  Apps.Backoffice.Backend.subscribers.rabbitmq.UpdateReviewSentimentToNegativeOnNegativeReviewDetected:
    class: ../../../../subscribers/rabbitmq/product-reviews/update-review-to-negative-sentiment/UpdateReviewSentimentToNegativeOnNegativeReviewDetected
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.update.to.negative.review.ToNegativeUpdateReviewSentimentUpdater"]
    tags: [{ "name": "domain-event-subscriber" }]